version: '3.8'
services:
  postgres:
    build:
        context: ./database
        dockerfile: Dockerfile
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      DATABASE_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8762:8762"

  discovery-server:
    container_name: discovery-server
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  restaurant:
    container_name: restaurant-service
    build:
      context: ./restaurant
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

  order:
    container_name: order-service
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "8084:8084"

    depends_on:
      postgres:
        condition: service_healthy

  payments:
    container_name: payments-service
    build:
      context: ./payments
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
  notification:
    container_name: notification-service
    build:
      context: ./notification
      dockerfile: Dockerfile
    ports:
      - "8085:8085"

  security:
    container_name: security-service
    build:
      context: ./security-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"


volumes:
  postgres:
  pgadmin:







