#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: restaurant-service
#          uri: lb://RESTAURANT-SERVICE
#          predicates:
#            - Path=/restaurant/**
#          filters:
#            - AuthenticationFilter
#
#        - id: security-service
#          uri: lb://SECURITY-SERVICE
#          predicates:
#            - Path=/auth/**
#
#  application:
#    name: API-GATEWAY
#
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/

#spring:
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders:
#              - "*"
#            allowCredentials: true
logging:
  level:
    org.springframework.web.cors: DEBUG